print("¡Conociendote!")
print()

TuNombre = input("¿Cómo te llamas?")
Comida = input("¿Cuál es tu comida favorita?")
Musica = input("¿Cuál es tu música favorita?")
DeDondeSos = input("De donde sos?")
print()

print("Tu nombre es", TuNombre)
print()
print("Tu comida favorita es", Comida)
print()
print("El dia estaria ideal para escuchar", Musica)
print()
print("vivis en", DeDondeSos)
print()
print("Gracias por dejarme conocerte!")
print("que tengas un gran dia!")